I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/cass route.rpy", line 18, in script
    menu:
  File "game/cass route.rpy", line 19, in <module>
    "Turn into a bat" if not a1:
NameError: name 'a1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/cass route.rpy", line 18, in script
    menu:
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/ast.py", line 1922, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/exports.py", line 1072, in menu
    condition = renpy.python.py_eval(condition)
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Radha\Downloads\renpy-7.6.1-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/cass route.rpy", line 19, in <module>
    "Turn into a bat" if not a1:
NameError: name 'a1' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 7.6.1.23060707
Crimson Nights 1.0
Wed Oct  4 21:04:18 2023
